services:
  gestaoBancaria_db:
    container_name: gestaoBancaria_db
    image: postgres:latest

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "gestaoBancaria"
      POSTGRES_DB: "gestaoBancaria"
      POSTGRES_PASSWORD: "SuperPassword@22"

    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./api
      dockerfile: DockerFile

    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - gestaoBancaria_db

  frontend:
    build:
      context: ./app
      dockerfile: DockerFile

    ports:
      - "3000:3000"

    depends_on:
      - backend

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg-data:
    driver: local
